### PR TITLE
Fixing isQuestions

### PR DESCRIPTION
**Pull request by shamoons**
https://github.com/spencermountain/compromise/issues/533

Not ready yet. Any thoughts?

### CODE REVIEW

**Comment by shamoons** [comment]
cc @spencermountain

**Comment by spencermountain** [comment]
hey shamoon, yeah that's fine. one note that `.has()` doesn't support full-regex, [here](https://github.com/spencermountain/compromise/blob/d5d1a17485c35b3896c2e87c1527d825a4766d76/src/subset/sentences/isQuestion.js#L35)
lemme know when it's ready.

**Comment by shamoons** [comment]
@spencermountain funny you should say that. I was having an impossible time with `.has`, detecting `..` at the end of sentences. Any suggestions on how to better handle it?

**Comment by spencermountain** [comment]
oh, good point. ergh - yeah, this may not be possible right now.
the elipses is stored in the 'whitespace', so they can't be queried with regex, or anything.
we should tag them as `#Elipses`. i'll [make an issue](https://github.com/spencermountain/compromise/issues/535) for this.

**Comment by shamoons** [comment]
Any way for me to match with regular regex? Can `ts` be converted to a string?

**Comment by shamoons** [comment]
cc @spencermountain

**Comment by spencermountain** [comment]
yeah, the regex match syntax is documented here
https://beta.observablehq.com/@spencermountain/compromise-match-syntax

**Comment by shamoons** [comment]
@spencermountain can I run `nlp(ts)` around here? https://github.com/spencermountain/compromise/pull/534/files#diff-1fe477e9e488dda77b528c63b7ab9adbR17

**Comment by spencermountain** [comment]
i'll add support for tagging the Elipses in v12, don't worry about that for now.

if you needed to do a regex, you could do `ts.out('text').match(reg)` re-parsing the whole object should not be necessary.

**Pull request closed without merging**
