### PR TITLE
No more whitespace

### PR DESCRIPTION
**Pull request by shamoons**
#536

### CODE REVIEW

**Comment by spencermountain** [comment]
hey, not sure about this one - i think the issue is during a contraction, an extra (silent) term is added and there are some complex operations with whitespace involved.
ie:
```
"she isn't    sleeping"
"she [is] [not]    sleeping"
```
at least, that's how it should work, but looks like something is going wrong there.

**Comment by shamoons** [comment]
@spencermountain thanks for the heads up. I'll take a look and see what I can do. Also, not sure if you got my email about being added to the Slack group. Slack.in doesn't seem to be working

**Comment by spencermountain** [comment]
cool, the slack link looks okay to me - http://slack.compromise.cool
did your email get bounced?

**Comment by spencermountain** [comment]
hey, i think I've got this contraction whitespace bug, gimme a couple minutes.

**Comment by spencermountain** [comment]
oh hey, i commented-out the `I'm what a poor boy` case. Is that british-queen-english, or something?

hey, btw, have you seen this?
https://github.com/nlp-compromise/compromise-stress/blob/master/src/question-forms/data.js

**Comment by spencermountain** [comment]
closing this for houskeeping, think it's fixed, but happy to merge other prs in the future.
cheers

**Comment by spencermountain** [comment]
closing this, think it's fixed
cheers

**Pull request closed without merging**
