### PR TITLE
Fractions toNumber

### PR DESCRIPTION
**Pull request by Jakeii**
Hey @spencermountain,

I started working on this and noticed way too late that you'd already done some similar improvements, when I pulled `dev` and saw your new fraction tests failing....

Mine does add support for converting text fractions to numbers and super long weird fractions 

```js
> nlp('two hundred and twelve and one twentieths').values().toNumber().all().out()
'212.05'
```

shall I continue to work on this? or maybe you can incorporate into yours.

### CODE REVIEW

**Comment by spencermountain** [comment]
hey @Jakeii ! Sorry about that! `and one twentieth` is a great feature - thank you for working on it.
For what it's worth, it should be stable until the new-year, if you wanted to continue working on it - having an open branch like that is great. 
Calculating the decimal is a great idea - watch out for `/0`!

Just thinking out loud -  `five and one twelfth`  =  `5.083`
* `doc.values()` should gobble up the whole thing,
* `doc.fractions()` would gobble up the `one twelfth` bit - wouldn't it?
Feel free to change anything you'd like - it's not all that clever, or well-written right now.

Just looking through the pr - great work! Let me know when it's ready.
cheers

**Comment by spencermountain** [comment]
i'm not quite sure what `doc.fractions()` is for, now that I'm thinking about it - the original idea was to parse `3/4` then it started doing `three out of four`, then it started doing `three fourths` - if it's rubbing-up against `n and three fourths` maybe it's doing too much.
ok, that's all!

**Comment by Jakeii** [comment]
cool! I'll continue then :)

I did start by trying to handle all fractions with .values() but it was interfering with ordinal conversions like `10th place` was converted to `0.1th place` or `5th of september` to `0.2th of september`, so I moved it under `.fractions()`

maybe a new function called toFloat or something would make more sense ?

**Comment by Jakeii** [comment]
> * `doc.values()` should gobble up the whole thing,

Ah I see I broke this when I moved it under fractions, that was the intention!

**Comment by spencermountain** [comment]
hey Jake, is there anything I can do to help get this one ready?
Hoping to cut a release this week, and would be great to get this in
No rush, otherwise.
cheers

**Comment by Jakeii** [comment]
> hey Jake, is there anything I can do to help get this one ready?
> Hoping to cut a release this week, and would be great to get this in
> No rush, otherwise.
> cheers
@spencermountain 
Yeah, keen to finish this! It was basically done, maybe some tweaks needed to how it is exposed. The tests were actually passing on my machine, I can't seem to see what's wrong in the GitHub action runner log?

**Comment by Jakeii** [comment]
@spencermountain any ideas regarding the tests?

**Comment by spencermountain** [comment]
ahh - haha, it's conflicting with `second quarter 2020` in the date-parsing tests.
I'll merge it to dev and fix it.
Nice work! Thank you for doing this.

**Comment by spencermountain** [comment]
oh, i love this project sometimes:

image

image

**Comment by Jakeii** [comment]
> ahh - haha, it's conflicting with `second quarter 2020` in the date-parsing tests.
> I'll merge it to dev and fix it.
> Nice work! Thank you for doing this.
Sweet!

A final thought from me, this changes `.fractions().toNumber()` and converts all fractions to decimals, not sure if that makes sense, fractions are numbers, possibly toFloat or toDecimal would make more sense? But I don't really know!

> ahh - haha, it's conflicting with `second quarter 2020` in the date-parsing tests.
> I'll merge it to dev and fix it.
> Nice work! Thank you for doing this.

ahaha beautiful

**Comment by spencermountain** [comment]
been working through a lot of these examples - really nice work on this.
May need some help on some edge-cases, but should be ready for a release early-next week, if not this one.

it's surprising how fractiony regular english is.  -  I really enjoyed the 0.5-time show while watching the superbowl, etc.
Also this stuff with Ordinal-fractions is great.
have a good day!

**Comment by spencermountain** [comment]
it may also be fun to run `.fractions()` on a big text and see what sort of false-positives it finds.  IMO, it shouldn't return things like 'half-baked' or 'third inning', or 'quarter past five' and stuff like that. I'm sure there's plenty of gotchas.

released as `1.2.0`

**Pull request merged**
