### PR TITLE
fix(plugins/dates): add dmy option to fix #1131

### LINKED ISSUE #1131: add dmy option
https://github.com/spencermountain/compromise/pull/1129#issuecomment-2251395409

### PR DESCRIPTION
**Pull request by hchiam**
add dmy option to fix #1131

based on discussion in another PR: https://github.com/spencermountain/compromise/pull/1129#issuecomment-2251395409

for future reference for myself and maybe helpful for other devs, **here's the path of references that led me to find the place i edited in the compromise-dates plugin code**: 

dates.js get() and others call parseDates > parse > parseRange > parseRanges > tryFull > parseDate > parse > explicit > parseExplicit > new Day() > Unit > spacetime (spacetime has a dmy option)

i saw spacetime used in other places and thought of adding `dmy: context.dmy` there too, but i kept my changes minimal for my first try in this pr

excluded the automatic changes to the package-lock version numbers

### CODE REVIEW

**Review by hchiam — COMMENTED** [review]
Ready for review.

**Comment by Fdawgs** [comment]
Great @hchiam, I think this also needs your suggested fix from https://github.com/spencermountain/compromise/pull/1129/files#r1690519347

**Comment by spencermountain** [comment]
amazing!
I'll release both fixes if I can, tomorrow
thank you!

**Comment by hchiam** [comment]
> Great @hchiam, I think this also needs your suggested fix from https://github.com/spencermountain/compromise/pull/1129/files#r1690519347

i'll work on a quick pr to get this in hopefully before @spencermountain creates the next release

**Pull request merged**
