### PR TITLE
Update currencies.js

### PR DESCRIPTION
**Pull request by DanielNetzer**
added Israeli currency

### CODE REVIEW

**Comment by spencermountain** [comment]
thanks Daniel!
I'll release this as `11.14.3` on monady, and also add this to v12, which is happening next week.
cheers

**Comment by DanielNetzer** [comment]
np, my pleasure. Found this library by mistake and it looked amazing. Still going over the code to understand how it works exactly

**Comment by spencermountain** [comment]
welcome! you may want to gander [this branch](https://github.com/spencermountain/compromise/tree/linked-list) instead.

**Comment by spencermountain** [comment]
released in v12. Cheers

**Pull request merged**
