### PR TITLE
Add match2 with history to plugins directory.

### PR DESCRIPTION
**Pull request by kelvinhammond**
Related to https://github.com/spencermountain/compromise/issues/765

### CODE REVIEW

**Comment by spencermountain** [comment]
hey this is great! Nice work.
Gonna merge it to dev and take it for a spin. Will ping you if I change anything non-cosmetic.
What a cool plugin!!

**Comment by spencermountain** [comment]
hey @kelvinhammond  what do you think? any feedback is welcome
https://github.com/spencermountain/compromise/tree/master/plugins/strict
I learned a lot going through this - thank you for doing it.

**Comment by kelvinhammond** [comment]
@spencermountain The README can be updated to say that it supports.

- [Method match functions](https://github.com/spencermountain/compromise/blob/master/plugins/strict/src/pikevm.js#L198)
  - [see format here](https://github.com/spencermountain/compromise/blob/master/plugins/strict/src/parser.js#L31)

Example: `(@hasContraction|@isTitleCase)+`

I forget when I added this but its supported and should be added to the README.

Looks good to me, thanks for adding it to the project. You can call it whatever you'd like. Why `strict`?

**Comment by spencermountain** [comment]
added! Thanks, yeah I was thinking it was a match-parser that would throw an error if it the input was wrong.
`compromise-formal` was the 2nd choice. Happy to change it to whatever.
Happy holidays.

**Comment by kelvinhammond** [comment]
Its a completely new match parser with its own syntax and features. I tried to implement what the current `match` supports but with the syntax being closer to an actual regex and supporting nested values and a few other issues with the original `match` method. 

In summary, it is a bit more strict but its also completely new with its own features. If its missing anything from the original `match`I may be able to implement them depending on the feature.

Happy holidays to you too.

**Comment by thegoatherder** [comment]
@spencermountain is this plugin still alive or dead? Doesn't seem to be in the plugins dir any more...

**Comment by kelvinhammond** [comment]
@thegoatherder @spencermountain I think it was removed, I could help maintain it if you'd like.

**Pull request merged**
