### PR TITLE
Issue #583 handle verbs w/ slashes

### PR DESCRIPTION
**Pull request by charlesLoder**
fixes: #583

### CODE REVIEW

**Comment by scagood** [comment]
Would this compensate for adverbs?
Say for example: `I would/would not like that.`

Also, could you add test cases for this?

**Comment by charlesLoder** [comment]
As is, no - it doesn't compensate for adverbs:
```javascript
let doc = `He hastily/speedily ran.`;
console.log(nlp(doc).adverbs().length);

>>> 1
```
Since `would` is a modal word, I'm not sure how compromise handles them. What I get is:
```javascript
let doc = `He would/would not like a puppy.`;
console.log(nlp(doc).verbs().out('array'));

>>> ['would', 'would', 'not like']
```

**Comment by spencermountain** [comment]
👏

**Comment by elliot-nelson** [comment]
Nice! :+1:

**Pull request merged**
